name: Build and Deploy to Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Determine Dockerfile
        id: dockerfile
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "Using Dockerfile_Production"
            echo "DOCKERFILE=Dockerfile_Production" >> $GITHUB_ENV
          else
            echo "Using Dockerfile_Development"
            echo "DOCKERFILE=Dockerfile_Development" >> $GITHUB_ENV
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: khanganonymous/cicd_development:latest
          file: ./${{ env.DOCKERFILE }}

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          timeout: 300s
          script: |
            docker pull khanganonymous/cicd_development:latest
            docker stop cicd_development || true
            docker rm cicd_development || true
            docker run -d -p 5253:5253 --name cicd_development khanganonymous/cicd_development:latest
