name: Build and Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t khanganonymous/cicd_development:latest -f ../Dockerfile_Development .
          docker push khanganonymous/cicd_development:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            docker pull khanganonymous/cicd_development:latest
            docker stop cicd_development || true
            docker rm cicd_development || true
            docker run -d -p 5253:5253 --name cicd_development khanganonymous/cicd_development:latest
